"""Stream a synthetic resource simulation into a running local Arena workspace.

The positions and insights are scripted fixtures; this tool makes no model calls.
"""

from __future__ import annotations

import argparse
import math
import os
import time
import uuid

from arena_adapter import AdapterError, ArenaAdapter


def event(sequence: int, source_time: float, kind: str, payload: dict) -> dict:
    return {"sequence": sequence, "source_time": source_time, "type": kind, "payload": payload}


def synthetic_batch(
    step: int, *, source_time: float, sequence: int, final: bool = False
) -> list[dict]:
    """Deterministic toy telemetry, including delayed evidence and its cited insight."""
    evidence_id = f"sample-evidence-{step:04d}"
    report_time = max(0.0, source_time - 0.4)
    interval = source_time / step if step and source_time > 0 else 1.0
    angle = (report_time / interval) * math.pi / 12
    entities = [
        {"id": "friendly-0", "label": "Scout A", "team": "friendly", "x": 7 + step % 8, "y": 9},
        {"id": "friendly-1", "label": "Scout B", "team": "friendly", "x": 8, "y": 6 + step % 8},
        {
            "id": "reported-0",
            "label": "Synthetic report",
            "team": "opponent",
            "source_time": report_time,
            "x": 20 + 3 * math.cos(angle),
            "y": 16 + 3 * math.sin(angle),
        },
    ]
    entries = [
        (
            "snapshot",
            {
                "entities": entities,
                "world": {
                    "width": 32,
                    "height": 32,
                    "nodes": [
                        {"id": 0, "x": 8, "y": 16},
                        {"id": 1, "x": 20, "y": 16},
                        {"id": 2, "x": 24, "y": 8},
                    ],
                },
                "scores": [step * 2, step],
            },
        ),
        (
            "evidence",
            {
                "records": [
                    {
                        "id": evidence_id,
                        "kind": "sighting",
                        "observed_at": report_time,
                        "received_at": source_time,
                        "summary": "Scripted synthetic report moves around objective 1.",
                        "entity_id": "reported-0",
                        "details": {"node_id": 1, "x": entities[2]["x"], "y": entities[2]["y"]},
                    }
                ]
            },
        ),
    ]
    if step % 4 == 0:
        entries.append(
            (
                "assessment",
                {
                    "status": "scripted",
                    "origin": "scripted",
                    "request_id": f"sample-cycle-{step:04d}",
                    "summary": (
                        "Synthetic fixture: repeated reports suggest attention near objective 1."
                    ),
                    "hypotheses": [
                        {
                            "claim": "This scripted report remains near objective 1.",
                            "evidence_ids": [evidence_id],
                            "alternative": "Another objective may receive later activity.",
                        }
                    ],
                    "forecast": {
                        "horizon_tick": int(source_time * 10) + 300,
                        "probabilities": [0.1, 0.6, 0.1, 0.2],
                    },
                    "cutoff_tick": int(source_time * 10),
                    "latency_seconds": 0,
                    "cost_usd": 0,
                },
            )
        )
    entries.append(("metric", {"name": "synthetic_tick", "value": step, "unit": "tick"}))
    if final:
        entries.append(
            (
                "lifecycle",
                {
                    "status": "completed",
                    "message": "Synthetic sample completed; no LLM calls were made.",
                },
            )
        )
    return [
        event(sequence + index, source_time, kind, payload)
        for index, (kind, payload) in enumerate(entries)
    ]


def options(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--url", default="http://127.0.0.1:8767")
    parser.add_argument("--name", default="Synthetic adapter walkthrough")
    parser.add_argument("--connection-name", default="Local simulation sample")
    parser.add_argument(
        "--session-id", help="stable ID for your external simulation; generated by default"
    )
    parser.add_argument("--steps", type=int, default=24)
    parser.add_argument(
        "--interval", type=float, default=1.0, help="wall-clock seconds between batches"
    )
    return parser.parse_args(argv)


def main(argv=None):
    args = options(argv)
    if (
        not 1 <= args.steps <= 10000
        or not math.isfinite(args.interval)
        or args.interval < 1
        or (args.steps - 1) * args.interval > 3600
    ):
        raise SystemExit(
            "steps must be 1..10000, interval at least 1 second, "
            "and sample duration at most 3600 seconds"
        )
    client = ArenaAdapter(args.url, token=os.environ.get("ARENA_INTEGRATION_TOKEN"))
    if not client.token:
        connection = client.connect(args.connection_name)
        print(f"Connected synthetic source {connection['id']}; token stays in memory.", flush=True)
    external_id = args.session_id or "sample-" + uuid.uuid4().hex
    sequence = 1
    print(
        f"Streaming scripted simulation {external_id}. No model calls or API credits.", flush=True
    )
    try:
        for step in range(args.steps):
            final = step == args.steps - 1
            batch = synthetic_batch(
                step, source_time=step * args.interval, sequence=sequence, final=final
            )
            sequence += len(batch)
            result = client.publish(
                external_id, args.name, batch, status="completed" if final else "running"
            )
            print(
                f"Step {step + 1}/{args.steps}: accepted {result['accepted_events']} events; "
                f"session {result['session']['id']}",
                flush=True,
            )
            if not final:
                time.sleep(args.interval)
    except KeyboardInterrupt:
        try:
            client.publish(
                external_id,
                args.name,
                [
                    event(
                        sequence,
                        step * args.interval,
                        "lifecycle",
                        {"status": "stopped", "message": "Sample adapter interrupted."},
                    )
                ],
                status="stopped",
            )
        except AdapterError:
            pass
        raise SystemExit(130) from None


if __name__ == "__main__":
    try:
        main()
    except (AdapterError, ValueError) as error:
        raise SystemExit(str(error)) from None
